# Generated by Django 4.2.1 on 2023-06-08 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj_predmeta',
            field=models.ForeignKey(blank=True, limit_choices_to={'uloga': 'Profesor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
