# Generated by Django 4.2.1 on 2023-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0003_rename_student_id_upisi_korisnik_id_upisi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloga',
            name='naziv_uloge',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('profesor', 'Profesor'), ('administrator', 'Administrator')], max_length=50, null=True),
        ),
    ]
