# Generated by Django 4.2.1 on 2023-06-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0006_alter_korisnici_status_alter_uloga_naziv_uloge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('izv', 'izvanredni'), ('red', 'redovni')], max_length=50),
        ),
        migrations.AlterField(
            model_name='korisnici',
            name='uloga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upis.uloga'),
        ),
    ]
