# Generated by Django 4.2.1 on 2023-06-09 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0007_alter_korisnici_status_alter_korisnici_uloga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj_predmeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
