# Generated by Django 4.2.2 on 2023-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0008_alter_predmeti_nositelj_predmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uloga',
            name='naziv_uloge',
        ),
        migrations.AddField(
            model_name='uloga',
            name='uloga',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
