# Generated by Django 4.2.2 on 2023-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0010_alter_predmeti_izborni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(blank=True, choices=[('not', 'Neupisan'), ('enr', 'Upisan'), ('pass', 'Polozen'), ('lst', 'Izgubio potpis')], max_length=50, null=True),
        ),
    ]
